### ISSUE TITLE
JNAerator cannot be compiled following the README

### ISSUE THREAD

**Issue by DevCybran** [nativelibs4java/JNAerator#104]
I tried to build JNAerator on Ubuntu 14.04 with a fresh install of maven2.

Upon issuing ```mvn clean install```, the following errors are reported:

```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error building POM (may not be this project's POM).


Project ID: com.nativelibs4java:jnaerator-parent:pom:0.13-SNAPSHOT

Reason: Cannot find parent: com.nativelibs4java:nativelibs4java-parent for project: com.nativelibs4java:jnaerator-parent:pom:0.13-SNAPSHOT for project com.nativelibs4java:jnaerator-parent:pom:0.13-SNAPSHOT


[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.reactor.MavenExecutionException: Cannot find parent: com.nativelibs4java:nativelibs4java-parent for project: com.nativelibs4java:jnaerator-parent:pom:0.13-SNAPSHOT for project com.nativelibs4java:jnaerator-parent:pom:0.13-SNAPSHOT
	at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:404)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:272)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.project.ProjectBuildingException: Cannot find parent: com.nativelibs4java:nativelibs4java-parent for project: com.nativelibs4java:jnaerator-parent:pom:0.13-SNAPSHOT for project com.nativelibs4java:jnaerator-parent:pom:0.13-SNAPSHOT
	at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1396)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(DefaultMavenProjectBuilder.java:823)
	at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromSourceFileInternal(DefaultMavenProjectBuilder.java:508)
	at org.apache.maven.project.DefaultMavenProjectBuilder.build(DefaultMavenProjectBuilder.java:200)
	at org.apache.maven.DefaultMaven.getProject(DefaultMaven.java:604)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:487)
	at org.apache.maven.DefaultMaven.getProjects(DefaultMaven.java:391)
	... 12 more
Caused by: org.apache.maven.project.ProjectBuildingException: Error getting POM for 'com.nativelibs4java:nativelibs4java-parent' from the repository: Unable to read local copy of metadata: Cannot read metadata from '/home/atlas/.m2/repository/com/nativelibs4java/nativelibs4java-parent/1.10-SNAPSHOT/maven-metadata-sonatype.xml': end tag name </body> must match start tag name <hr> from line 5 (position: TEXT seen ...</center>\r\n</body>... @6:8) 
  com.nativelibs4java:nativelibs4java-parent:pom:1.10-SNAPSHOT


 for project com.nativelibs4java:nativelibs4java-parent
	at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:592)
	at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(DefaultMavenProjectBuilder.java:1392)
	... 18 more
Caused by: org.apache.maven.artifact.resolver.ArtifactResolutionException: Unable to read local copy of metadata: Cannot read metadata from '/home/atlas/.m2/repository/com/nativelibs4java/nativelibs4java-parent/1.10-SNAPSHOT/maven-metadata-sonatype.xml': end tag name </body> must match start tag name <hr> from line 5 (position: TEXT seen ...</center>\r\n</body>... @6:8) 
  com.nativelibs4java:nativelibs4java-parent:pom:1.10-SNAPSHOT



	at org.apache.maven.artifact.transform.SnapshotTransformation.transformForResolve(SnapshotTransformation.java:68)
	at org.apache.maven.artifact.transform.DefaultArtifactTransformationManager.transformForResolve(DefaultArtifactTransformationManager.java:55)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:145)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:90)
	at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(DefaultMavenProjectBuilder.java:558)
	... 19 more
Caused by: org.apache.maven.artifact.repository.metadata.RepositoryMetadataResolutionException: Unable to read local copy of metadata: Cannot read metadata from '/home/atlas/.m2/repository/com/nativelibs4java/nativelibs4java-parent/1.10-SNAPSHOT/maven-metadata-sonatype.xml': end tag name </body> must match start tag name <hr> from line 5 (position: TEXT seen ...</center>\r\n</body>... @6:8) 
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolve(DefaultRepositoryMetadataManager.java:175)
	at org.apache.maven.artifact.transform.AbstractVersionTransformation.resolveVersion(AbstractVersionTransformation.java:65)
	at org.apache.maven.artifact.transform.SnapshotTransformation.transformForResolve(SnapshotTransformation.java:63)
	... 23 more
Caused by: org.apache.maven.artifact.repository.metadata.RepositoryMetadataReadException: Cannot read metadata from '/home/atlas/.m2/repository/com/nativelibs4java/nativelibs4java-parent/1.10-SNAPSHOT/maven-metadata-sonatype.xml': end tag name </body> must match start tag name <hr> from line 5 (position: TEXT seen ...</center>\r\n</body>... @6:8) 
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.readMetadata(DefaultRepositoryMetadataManager.java:323)
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.loadMetadata(DefaultRepositoryMetadataManager.java:275)
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.mergeMetadata(DefaultRepositoryMetadataManager.java:198)
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.resolve(DefaultRepositoryMetadataManager.java:166)
	... 25 more
Caused by: org.codehaus.plexus.util.xml.pull.XmlPullParserException: end tag name </body> must match start tag name <hr> from line 5 (position: TEXT seen ...</center>\r\n</body>... @6:8) 
	at hidden.org.codehaus.plexus.util.xml.pull.MXParser.parseEndTag(MXParser.java:1698)
	at hidden.org.codehaus.plexus.util.xml.pull.MXParser.nextImpl(MXParser.java:1143)
	at hidden.org.codehaus.plexus.util.xml.pull.MXParser.next(MXParser.java:1105)
	at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.parseMetadata(MetadataXpp3Reader.java:502)
	at org.apache.maven.artifact.repository.metadata.io.xpp3.MetadataXpp3Reader.read(MetadataXpp3Reader.java:951)
	at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager.readMetadata(DefaultRepositoryMetadataManager.java:310)
	... 28 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Fri Oct 23 16:34:10 CEST 2015
[INFO] Final Memory: 2M/30M
[INFO] ------------------------------------------------------------------------
```

Unfortunately I am not familiar with maven, but it looks like there is an XML parser exception in one of your dependencies?

**Comment by pabx06** [comment]
same here

**Comment by cleverpig** [comment]
same here
